package com.sergioricart.kafka_project.user.infrastructure.api.contoller;

import com.sergioricart.kafka_project.autogenerated.events.user.UserCreatedEvent;
import com.sergioricart.kafka_project.common.infrastructure.event.producer.KafkaProducer;
import com.sergioricart.kafka_project.user.domain.entiry.Role;
import com.sergioricart.kafka_project.user.domain.entiry.User;
import com.sergioricart.kafka_project.user.domain.port.UserRepository;
import com.sergioricart.kafka_project.user.infrastructure.api.dto.request.UserCreatedRequest;
import com.sergioricart.kafka_project.user.infrastructure.api.dto.response.UserResponse;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;
import java.util.UUID;

@Slf4j
@RestController
@RequestMapping("/api/v1/users")
@RequiredArgsConstructor
public class UserController {

    private final KafkaProducer kafkaProducer;

    private final UserRepository userRepository;

    @Value("${app.kafka.topics.user}")
    private String topic;

    @PostMapping("/create")
    public ResponseEntity<?> createUser(@Valid @RequestBody UserCreatedRequest userDto) {

        log.debug("Creating user {}", userDto);


        UserCreatedEvent userCreatedEvent = UserCreatedEvent.newBuilder()
                .setFirstName(userDto.getFirstName())
                .setLastName(userDto.getLastName())
                .setEmail(userDto.getEmail())
                .setRole(Role.USER.toString())
                .setPassword(userDto.getPassword())
                .setTimestamp(System.currentTimeMillis())
                .build();

        kafkaProducer.send(topic, userCreatedEvent);

        return ResponseEntity.status(HttpStatus.CREATED).build();

    }

    @GetMapping("/{id}")
    public ResponseEntity<UserResponse> getUser(@PathVariable String id) {

        Optional<UserResponse> optionalUser = userRepository.findById(id);

        return optionalUser
                .map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }


}
