package com.sergioricart.kafka_project.user.infrastructure.event.specific;

import com.sergioricart.kafka_project.autogenerated.events.user.UserCreatedEvent;
import com.sergioricart.kafka_project.common.infrastructure.event.consumer.EventSpecificConsummer;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserCreatedSpecificConsumer implements EventSpecificConsummer<UserCreatedEvent> {

    @Override
    public void accept(Message<UserCreatedEvent> genericRecordMessage) {

        UserCreatedEvent userCreatedEvent = genericRecordMessage.getPayload();

        log.info("UserCreatedEvent: {}", userCreatedEvent);

    }

    @Override
    public String getSchema() {
        return UserCreatedEvent.getClassSchema().getFullName();
    }
}
