package com.sergioricart.kafka_project.user.infrastructure.event.specific;

import com.sergioricart.kafka_project.autogenerated.events.user.UserEmailUpdatedEvent;
import com.sergioricart.kafka_project.common.application.Mediator;
import com.sergioricart.kafka_project.common.infrastructure.event.consumer.EventSpecificConsummer;
import com.sergioricart.kafka_project.user.application.emailUpdated.UserEmailUpdatedCommand;
import com.sergioricart.kafka_project.user.infrastructure.event.mapper.UserEventMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserEmailUpdatedSpecificConsumer implements EventSpecificConsummer<UserEmailUpdatedEvent> {

    private final Mediator mediator;
    private final UserEventMapper userEventMapper;

    @Override
    public void accept(Message<UserEmailUpdatedEvent> genericRecordMessage) {

        log.info("Received UserEmailUpdatedSpecificConsumer from UserEmailUpdatedEvent");

        UserEmailUpdatedCommand command = userEventMapper.mapToUserEmailUpdatedCommand(genericRecordMessage.getPayload());
        mediator.dispatch(command);

    }

    @Override
    public String getSchema() {
        return UserEmailUpdatedEvent.getClassSchema().getFullName();
    }
}
