/**
 * NOTA ARQUITECTURAL: Este consumer procesa eventos del propio dominio
 * de usuarios, lo cual solo tiene sentido si un servicio externo es el
 * que crea/borra/actualiza usuarios y este servicio sincroniza su BD
 * escuchando esos eventos.
 *
 * Si este servicio es el único dueño del dominio de usuarios, estos
 * consumers no tienen utilidad real. Los SpecificConsumers útiles serían
 * los de otros dominios a los que este servicio necesite reaccionar,
 * por ejemplo: OrderCreatedSpecificConsumer, PaymentCompletedSpecificConsumer.
 */






/*
package com.sergioricart.kafka_project.user.infrastructure.event.consumer.specific;

import com.sergioricart.kafka_project.autogenerated.events.user.UserUpdatedEvent;
import com.sergioricart.kafka_project.common.application.Mediator;
import com.sergioricart.kafka_project.common.infrastructure.event.consumer.EventSpecificConsummer;
import com.sergioricart.kafka_project.user.application.kafka.updated.UserUpdatedCommand;
import com.sergioricart.kafka_project.user.infrastructure.event.mapper.UserEventMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserUpdatedSpecificConsumer implements EventSpecificConsummer<UserUpdatedEvent> {

    private final Mediator mediator;
    private final UserEventMapper userEventMapper;

    @Override
    public void accept(Message<UserUpdatedEvent> genericRecordMessage) {

        log.info("Received UserUpdatedSpecificConsumer from UserUpdatedEvent {}", genericRecordMessage.getPayload());

        UserUpdatedCommand command = userEventMapper.mapToUserUpdatedCommand(genericRecordMessage.getPayload());

        mediator.dispatch(command);

    }

    @Override
    public String getSchema() {
        return UserUpdatedEvent.getClassSchema().getFullName();
    }
}
*/
