/**
 * NOTA ARQUITECTURAL: Este consumer procesa eventos del propio dominio
 * de usuarios, lo cual solo tiene sentido si un servicio externo es el
 * que crea/borra/actualiza usuarios y este servicio sincroniza su BD
 * escuchando esos eventos.
 *
 * Si este servicio es el único dueño del dominio de usuarios, estos
 * consumers no tienen utilidad real. Los SpecificConsumers útiles serían
 * los de otros dominios a los que este servicio necesite reaccionar,
 * por ejemplo: OrderCreatedSpecificConsumer, PaymentCompletedSpecificConsumer.
 */








/*
package com.sergioricart.kafka_project.user.infrastructure.event.consumer.specific;

import com.sergioricart.kafka_project.autogenerated.events.user.UserDeletedEvent;
import com.sergioricart.kafka_project.common.application.Mediator;
import com.sergioricart.kafka_project.common.infrastructure.event.consumer.EventSpecificConsummer;
import com.sergioricart.kafka_project.user.application.kafka.deleted.UserDeletedCommand;
import com.sergioricart.kafka_project.user.infrastructure.event.mapper.UserEventMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserDeletedSpecificConsumer implements EventSpecificConsummer<UserDeletedEvent> {

    private final Mediator mediator;
    private final UserEventMapper userEventMapper;

    @Override
    public void accept(Message<UserDeletedEvent> genericRecordMessage) {

        log.info("Received UserDeletedSpecificConsumer from UserDeletedEvent");

        UserDeletedCommand command = userEventMapper.mapToUserDeletedCommand(genericRecordMessage.getPayload());
        mediator.dispatch(command);

    }

    @Override
    public String getSchema() {
        return UserDeletedEvent.getClassSchema().getFullName();
    }
}
*/
