package com.sergioricart.kafka_project.user.infrastructure.event.consumer.specific;

import com.sergioricart.kafka_project.autogenerated.events.user.UserCreatedEvent;
import com.sergioricart.kafka_project.common.application.Mediator;
import com.sergioricart.kafka_project.common.infrastructure.event.consumer.EventSpecificConsummer;
import com.sergioricart.kafka_project.user.application.kafka.created.UserCreatedCommand;
import com.sergioricart.kafka_project.user.infrastructure.event.mapper.UserEventMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserCreatedSpecificConsumer implements EventSpecificConsummer<UserCreatedEvent> {

    private final Mediator mediator;
    private final UserEventMapper userEventMapper;

    @Override
    public void accept(Message<UserCreatedEvent> genericRecordMessage) {

        log.info("Received UserCreatedSpecificConsumer from UserCreatedEvent {}", genericRecordMessage.getPayload());

        UserCreatedCommand command = userEventMapper.mapToUserCreatedCommand(genericRecordMessage.getPayload());
        mediator.dispatch(command);

    }

    @Override
    public String getSchema() {
        return UserCreatedEvent.getClassSchema().getFullName();
    }
}
