package com.sergioricart.kafka_project.user.infrastructure.event.consumer.specific;

import com.sergioricart.kafka_project.autogenerated.events.user.UserUpdatedEvent;
import com.sergioricart.kafka_project.common.application.Mediator;
import com.sergioricart.kafka_project.common.infrastructure.event.consumer.EventSpecificConsummer;
import com.sergioricart.kafka_project.user.application.kafka.updated.UserUpdatedCommand;
import com.sergioricart.kafka_project.user.infrastructure.event.mapper.UserEventMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserUpdatedSpecificConsumer implements EventSpecificConsummer<UserUpdatedEvent> {

    private final Mediator mediator;
    private final UserEventMapper userEventMapper;

    @Override
    public void accept(Message<UserUpdatedEvent> genericRecordMessage) {

        log.info("Received UserUpdatedSpecificConsumer from UserUpdatedEvent {}", genericRecordMessage.getPayload());

        UserUpdatedCommand command = userEventMapper.mapToUserUpdatedCommand(genericRecordMessage.getPayload());

        mediator.dispatch(command);

    }

    @Override
    public String getSchema() {
        return UserUpdatedEvent.getClassSchema().getFullName();
    }
}
