package com.sergioricart.kafkaSpringUserService.user.infrastructure.event.mapper;

import com.sergioricart.kafkaSpringUserService.autogenerated.events.user.*;
import com.sergioricart.kafkaSpringUserService.common.infrastructure.event.util.MapperUtils;
import com.sergioricart.kafkaSpringUserService.user.domain.event.UserCreatedDomainEvent;
import com.sergioricart.kafkaSpringUserService.user.domain.event.UserDeletedDomainEvent;
import com.sergioricart.kafkaSpringUserService.user.domain.event.UserUpdatedDomainEvent;
import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface UserEventMapper extends MapperUtils {

    UserCreatedEvent mapToUserCreatedEvent(UserCreatedDomainEvent event);

    UserDeletedEvent mapToUserDeletedEvent(UserDeletedDomainEvent event);

    UserUpdatedEvent mapToUserUpdatedEvent(UserUpdatedDomainEvent event);

}
