package com.sergioricart.kafka_project.user.infrastructure.event.mapper;

import com.sergioricart.kafka_project.autogenerated.events.user.*;
import com.sergioricart.kafka_project.common.infrastructure.event.util.MapperUtils;
import com.sergioricart.kafka_project.user.domain.event.UserCreatedDomainEvent;
import com.sergioricart.kafka_project.user.domain.event.UserDeletedDomainEvent;
import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface UserEventMapper extends MapperUtils {

/*    UserCreatedCommand mapToUserCreatedCommand(UserCreatedEvent event);

    UserUpdatedCommand mapToUserUpdatedCommand(UserUpdatedEvent event);

    UserDeletedCommand mapToUserDeletedCommand(UserDeletedEvent event);

    UserDeactivatedEvent mapToUserDeactivatedEvent(UserDeactivatedDomainEvent event);

    UserVerificationRequestedEvent mapToUserVerificationRequestedEvent(UserVerificationRequestedDomainEvent event);*/

    UserCreatedEvent mapToUserCreatedEvent(UserCreatedDomainEvent event);

    UserDeletedEvent mapToUserDeletedEvent(UserDeletedDomainEvent event);



}
