package com.sergioricart.kafka_project.user.infrastructure.event.mapper;

import com.sergioricart.kafka_project.autogenerated.events.user.UserCreatedEvent;
import com.sergioricart.kafka_project.autogenerated.events.user.UserDeletedEvent;
import com.sergioricart.kafka_project.autogenerated.events.user.UserEmailUpdatedEvent;
import com.sergioricart.kafka_project.common.infrastructure.event.util.MapperUtils;
import com.sergioricart.kafka_project.user.application.created.UserCreatedCommand;
import com.sergioricart.kafka_project.user.application.deleted.UserDeletedCommand;
import com.sergioricart.kafka_project.user.application.emailUpdated.UserEmailUpdatedCommand;
import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface UserEventMapper extends MapperUtils {

    UserCreatedCommand mapToUserCreatedCommand(UserCreatedEvent event);

    UserEmailUpdatedCommand mapToUserEmailUpdatedCommand(UserEmailUpdatedEvent event);

    UserDeletedCommand mapToUserDeletedCommand(UserDeletedEvent event);

}
