package com.sergioricart.kafka_project.user.infrastructure.api;

import com.sergioricart.kafka_project.autogenerated.events.user.UserCreatedEvent;
import com.sergioricart.kafka_project.common.infrastructure.event.producer.KafkaProducer;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/users")
@RequiredArgsConstructor
public class UserController {

    private final KafkaProducer kafkaProducer;

    @GetMapping("/create")
    public void createUser() {

        System.out.println("Creating user");

        UserCreatedEvent userCreatedEvent = UserCreatedEvent.newBuilder()
                .setId(1L)
                .setEmail("sergioricart@gmail.com")
                .setFirstname("Sergio")
                .setLastname("Ricart")
                .setRole("USER")
                .setTimestamp(System.currentTimeMillis())
                .build();

        kafkaProducer.send("user.events", userCreatedEvent);
    }


}
