package com.sergioricart.kafka_project.user.infrastructure.api;

import com.sergioricart.kafka_project.autogenerated.events.user.UserCreatedEvent;
import com.sergioricart.kafka_project.common.infrastructure.event.producer.KafkaProducer;
import com.sergioricart.kafka_project.user.domain.entiry.User;
import com.sergioricart.kafka_project.user.domain.port.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@RestController
@RequestMapping("/api/v1/users")
@RequiredArgsConstructor
public class UserController {

    private final KafkaProducer kafkaProducer;

    private final UserRepository userRepository;


    @GetMapping("/create")
    public void createUser() {

        System.out.println("Creating user");

        UserCreatedEvent userCreatedEvent = UserCreatedEvent.newBuilder()
                .setId(1L)
                .setEmail("sergioricart@gmail.com")
                .setFirstname("Sergio")
                .setLastname("Ricart")
                .setRole("USER")
                .setTimestamp(System.currentTimeMillis())
                .build();

        kafkaProducer.send("user.events", userCreatedEvent);
    }

    @GetMapping("/{id}")
    public ResponseEntity<User> getUser(@PathVariable Long id) {
        Optional<User> optionalUser = userRepository.findById(id);

        return optionalUser
                .map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }


}
