package com.sergioricart.kafka_project.user.infrastructure.api;

import com.sergioricart.kafka_project.autogenerated.events.user.UserCreatedEvent;
import com.sergioricart.kafka_project.common.infrastructure.event.producer.KafkaProducer;
import com.sergioricart.kafka_project.user.domain.entiry.User;
import com.sergioricart.kafka_project.user.domain.port.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/users")
@RequiredArgsConstructor
public class UserController {

    private final KafkaProducer kafkaProducer;

    private final UserRepository userRepository;

    @Value("${app.kafka.topics.user}")
    private String topic;


    @GetMapping("/create")
    public void createUser() {

        System.out.println("Creating user");

        String uuid = UUID.randomUUID().toString();

        UserCreatedEvent userCreatedEvent = UserCreatedEvent.newBuilder()
                .setId(uuid)
                .setEmail("sergioricart@gmail.com")
                .setFirstName("Sergio")
                .setLastName("Ricart")
                .setRole("USER")
                .setTimestamp(System.currentTimeMillis())
                .build();

        kafkaProducer.send(topic, userCreatedEvent);
    }

    @GetMapping("/{id}")
    public ResponseEntity<User> getUser(@PathVariable String id) {
        Optional<User> optionalUser = userRepository.findById(id);

        return optionalUser
                .map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }


}
